# Note: Requires docker compose 2.0.0+
#
# Usage: 
#   docker-compose up -d
# Alternative (without docker compose):
#   docker build -t appium/appium:local ./Appium/Dockerfile
#   docker run --privileged -d -p 4723:4723 -v /dev/bus/usb:/dev/bus/usb -e ANDROID_HOME=/usr/lib/android-sdk -e APPIUM_ADDITIONAL_PARAMS="--allow-insecure=adb_shell" --name appium-container appium/appium:local
version: '3.8'
name: appium

services:
  # Appium Docker Android  
  android-server:
    container_name: android
    build: 
      context: ./Appium
      dockerfile: Dockerfile
    ports:
      - 4723:4723
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - ANDROID_HOME=/usr/lib/android-sdk
      - APPIUM_ADDITIONAL_PARAMS=--allow-insecure=adb_shell
      # - CONNECT_TO_GRID=true
      # - SELENIUM_HOST=selenium_hub
      # Enable it for msite testing
      #- BROWSER_NAME=chrome